### ISSUE TITLE
Circular dependencies prohibit consumption using Rollup

### ISSUE THREAD

**Issue by badeball** [protobufjs/protobuf.js#1402]
protobuf.js version: v6.8.8 (but I can see the issue being present in latest master at time of writing)

The issue experienced here is a bit tricky, but due to circular dependencies in the code, it makes it impossible to package this dependency using EG. [rollup](https://rollupjs.org/), as stated [here](https://github.com/rollup/rollup/issues/2747) and with a repository to reproduce it [here](https://github.com/mmacfadden/rollup-protobufjs). This incidentally (?) works when consuming it normally via node, due to how they handle [circular references](https://nodejs.org/api/modules.html#modules_cycles).

I would really appriciate it if this was considered a bug.

Using [madge](https://github.com/pahen/madge), it's easy to detect circular dependencies in the code.

```
$ git clone git@github.com:protobufjs/protobuf.js.git
$ cd protobuf.js/
$ npx madge --circular src/index.js 
Processed 33 files (769ms) 

✖ Found 28 circular dependencies!

1) enum.js > namespace.js > field.js
2) enum.js > namespace.js > field.js > object.js > util.js
3) enum.js > namespace.js > field.js > object.js > util.js > root.js
4) field.js > object.js > util.js > root.js
5) namespace.js > field.js > object.js > util.js > root.js
6) field.js > object.js > util.js > root.js > oneof.js
7) object.js > util.js > root.js > oneof.js
8) util.js > root.js > oneof.js
9) util.js > root.js
10) converter.js > enum.js > namespace.js > field.js > object.js > util.js > type.js
11) enum.js > namespace.js > field.js > object.js > util.js > type.js > decoder.js
12) util.js > type.js > decoder.js > types.js
13) util.js > type.js > decoder.js
14) enum.js > namespace.js > field.js > object.js > util.js > type.js > encoder.js
15) util.js > type.js > encoder.js
16) enum.js > namespace.js > field.js > object.js > util.js > type.js
17) field.js > object.js > util.js > type.js
18) field.js > object.js > util.js > type.js > mapfield.js
19) util.js > type.js > mapfield.js
20) util/minimal.js > util/longbits.js
21) namespace.js > field.js > object.js > util.js > type.js
22) object.js > util.js > type.js > service.js > method.js
23) util.js > type.js > service.js > method.js
24) namespace.js > field.js > object.js > util.js > type.js > service.js
25) util.js > type.js > service.js
26) util.js > type.js
27) enum.js > namespace.js > field.js > object.js > util.js > type.js > verifier.js
28) util.js > type.js > verifier.js
```

**Comment by alekspetrov** [comment]
+ 1 the same issue

**Comment by dandymon** [comment]
+1 too

**Comment by hasparus** [comment]
👋

**Comment by HAHAHA44** [comment]
After I update my rollup to `v2.23.0` and using @rollup/plugin-commonjs, my issue is fixed.

The most important is that I set the transformMixedEsModules to true.
`commonjs({ transformMixedEsModules: true, })`

**Comment by serkangunes** [comment]
@HAHAHA44 I have followed what you have mentioned but I am still having the same issue

**Comment by nateshmbhat** [comment]
same issue here also :/

**Comment by lilingling3** [comment]
i have same issue

**Comment by saxon111** [comment]
same issue, protobufjs version 6.10.2, I use rollup to bundle the project. anyone solved it ?

**Comment by btakita** [comment]
Same issue. Any plan to fix this?

**Comment by huachaoliu** [comment]
Same issue. Now I have to use webpack.

**Comment by davidjgoss** [comment]
Plot twist: https://github.com/rollup/plugins/pull/658

> This PR finally adds general support for circular dependencies to the commonjs plugin.

**Comment by yongjun21** [comment]
https://github.com/rollup/plugins/pull/658 did not fully fix this. See disclaimer in: https://github.com/rollup/plugins/pull/658#issue-526192287.

> While this PR adds support for circular references, it does not add support for exact execution order for inline require statements. As some packages with circular references also rely on that, they may still not work. But often, they can now be made to work by manually tweaking the execution order via strategic imports

**Comment by nateshmbhat** [comment]
is this issue fixed for anyone ?

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
