### ISSUE TITLE
Use of eval is strongly discouraged

### ISSUE THREAD

**Issue by imoye** [protobufjs/protobuf.js#1754]
protobuf.js version: 6.10.2

https://rollupjs.org/guide/en/#avoiding-eval
node_modules/@protobufjs/inquire/index.js

```js
function inquire(moduleName) {
try {
        var mod = eval("quire".replace(/^/,"re"))(moduleName); // eslint-disable-line no-eval
                      ^
        if (mod && (mod.length || Object.keys(mod).length))
        return mod;
```

**Comment by metr-o** [comment]
vouch

**Comment by gunta** [comment]
+1

**Comment by edevil** [comment]
`eval()` is also not available on certain environments such as Cloudflare Workers, which prevents this module, or anything that depends on it, from being used.

**Comment by kaiyoma** [comment]
Getting these errors during a Vite build:

```
00:22:03  common/temp/node_modules/.pnpm/@protobufjs+inquire@1.1.0/node_modules/@protobufjs/inquire/index.js (12:18) Use of eval in "common/temp/node_modules/.pnpm/@protobufjs+inquire@1.1.0/node_modules/@protobufjs/inquire/index.js" is strongly discouraged as it poses security risks and may cause issues with minification.
00:23:24  common/temp/node_modules/.pnpm/@protobufjs+inquire@1.1.0/node_modules/@protobufjs/inquire/index.js (12:18) Use of eval in "common/temp/node_modules/.pnpm/@protobufjs+inquire@1.1.0/node_modules/@protobufjs/inquire/index.js" is strongly discouraged as it poses security risks and may cause issues with minification.
00:24:32  common/temp/node_modules/.pnpm/@protobufjs+inquire@1.1.0/node_modules/@protobufjs/inquire/index.js (12:18) Use of eval in "common/temp/node_modules/.pnpm/@protobufjs+inquire@1.1.0/node_modules/@protobufjs/inquire/index.js" is strongly discouraged as it poses security risks and may cause issues with minification.
00:24:42  common/temp/node_modules/.pnpm/@protobufjs+inquire@1.1.0/node_modules/@protobufjs/inquire/index.js (12:18) Use of eval in "common/temp/node_modules/.pnpm/@protobufjs+inquire@1.1.0/node_modules/@protobufjs/inquire/index.js" is strongly discouraged as it poses security risks and may cause issues with minification.
```

**Comment by Aleksandr-JS-Developer** [comment]
It's not entirely clear why this is needed at all?
Why not `var mod = require(moduleName);`?

**Comment by tsemachh** [comment]
Same goes for Chrome Extensions using Manifest V3 - where it's also forbidden to use eval

**Comment by davideberlein** [comment]
This is a huge issue for us as the page we are integrating into forbids `eval` via CSP

**Comment by AntiMoron** [comment]
same here

**Comment by AntiMoron** [comment]
https://github.com/protobufjs/protobuf.js/pull/1941

I give it a try, more tests are needed.

**Comment by kaiyoma** [comment]
In addition to the Vite errors, this issue causes runtime CSP errors in Firefox:

```
Content-Security-Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
```

Clicking the link in the browser console error takes you here:

![image](https://github.com/protobufjs/protobuf.js/assets/10719780/f1157ceb-15ea-4380-b326-0c10072555ed)

**Comment by ngbrown** [comment]
I use this [patch-package](https://www.npmjs.com/package/patch-package) file:

<details>

<summary>patches/protobufjs+7.2.5.patch</summary>

```patch
diff --git a/node_modules/protobufjs/dist/light/protobuf.js b/node_modules/protobufjs/dist/light/protobuf.js
index 5727c45..3004e3d 100644
--- a/node_modules/protobufjs/dist/light/protobuf.js
+++ b/node_modules/protobufjs/dist/light/protobuf.js
@@ -876,6 +876,10 @@ module.exports = inquire;
  * @returns {?Object} Required module if available and not empty, otherwise `null`
  */
 function inquire(moduleName) {
+    // Don't use eval with CSP in a browser: https://github.com/protobufjs/protobuf.js/pull/1548
+    if (typeof document !== "undefined") {
+        return null;
+    }
     try {
         var mod = eval("quire".replace(/^/,"re"))(moduleName); // eslint-disable-line no-eval
         if (mod && (mod.length || Object.keys(mod).length))
diff --git a/node_modules/protobufjs/dist/minimal/protobuf.js b/node_modules/protobufjs/dist/minimal/protobuf.js
index 87e6f55..d5e2d9e 100644
--- a/node_modules/protobufjs/dist/minimal/protobuf.js
+++ b/node_modules/protobufjs/dist/minimal/protobuf.js
@@ -658,6 +658,10 @@ module.exports = inquire;
  * @returns {?Object} Required module if available and not empty, otherwise `null`
  */
 function inquire(moduleName) {
+    // Don't use eval with CSP in a browser: https://github.com/protobufjs/protobuf.js/pull/1548
+    if (typeof document !== "undefined") {
+        return null;
+    }
     try {
         var mod = eval("quire".replace(/^/,"re"))(moduleName); // eslint-disable-line no-eval
         if (mod && (mod.length || Object.keys(mod).length))
diff --git a/node_modules/protobufjs/dist/protobuf.js b/node_modules/protobufjs/dist/protobuf.js
index cda26c5..012e2f5 100644
--- a/node_modules/protobufjs/dist/protobuf.js
+++ b/node_modules/protobufjs/dist/protobuf.js
@@ -876,6 +876,10 @@ module.exports = inquire;
  * @returns {?Object} Required module if available and not empty, otherwise `null`
  */
 function inquire(moduleName) {
+    // Don't use eval with CSP in a browser: https://github.com/protobufjs/protobuf.js/pull/1548
+    if (typeof document !== "undefined") {
+        return null;
+    }
     try {
         var mod = eval("quire".replace(/^/,"re"))(moduleName); // eslint-disable-line no-eval
         if (mod && (mod.length || Object.keys(mod).length))
diff --git a/node_modules/protobufjs/src/util.js b/node_modules/protobufjs/src/util.js
index 6c50899..bd9a61d 100644
--- a/node_modules/protobufjs/src/util.js
+++ b/node_modules/protobufjs/src/util.js
@@ -199,6 +199,7 @@ util.setProperty = function setProperty(dst, path, value) {
     return setProp(dst, path, value);
 };
 
+if (!util.hasOwnProperty("decorateRoot")){
 /**
  * Decorator root (TypeScript).
  * @name util.decorateRoot
@@ -210,3 +211,4 @@ Object.defineProperty(util, "decorateRoot", {
         return roots["decorated"] || (roots["decorated"] = new (require("./root"))());
     }
 });
+}
```

</details>

The `if (!util.hasOwnProperty("decorateRoot"))` part is to prevent an error of re-defining the same property when using HMR.

**Comment by jakub-g** [comment]
To try to move forward with this and close the Content Security Policy threads like #997, **could some maintainer explain what problem the usage of `eval` inside `inquire` resolves precisely?** 

❓ Maybe the problem is no longer relevant?

By doing some archeology, it seems that `eval` was shipped many years ago due to webpack 4 automagically bundling `Buffer` for the web when it noticed `require`.

Note that webpack 5 (released Nov 2020) has broke compat on this, **and longer automagically ships nodejs polyfills.** 

So if that's the only reason, I'd suggest to cut a major version of protobufjs (8.0), and remove the usage of `eval`.

- https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

- https://webpack.js.org/migrate/5/

- https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5

**Comment by KAMAELUA** [comment]
Any updates? This completely breaks packaging ESM package because `require` is not defined and this `eval` is always running it.

**Comment by alaingiller** [comment]
I also got the problem while using @opentelemetry/exporter-trace-otlp-proto so I switch to @opentelemetry/exporter-trace-otlp-http. Less performant, but more secure at least...

**Comment by graham-atom** [comment]
I am also seeing this warning when building with vite, any updates?

**Comment by morzel85** [comment]
Just got this error (July 2024)...

**Comment by starseeker00** [comment]
I try to use this package in Cloudflare Workers, and have the same trouble with the usage of `eval()`. 
Any ideas to solve this problem? Thanks for helping.

**Comment by sebadob** [comment]
This is very annoying for sure, but I have a fix that is at leat not too annoying to apply.

First to make clear for which situation this works. I am only using the `protobufjs` dependency to encode / decode messages between frontend and backend. I am not accessing any grpc-web services or anything like that. I am compiling into `es6` compatible `static_module`s:

```bash
./node_modules/protobufjs-cli/bin/pbjs \
    --es6 -w es6 \
    -t static-module \
    --no-verify --no-convert --no-delimited --no-service --null-defaults \
    -o src/lib/api/types.js \
    ../proto/*.proto
```

This step can't be executed again after the the `eval` fix has been applied. This means you need to get rid of any installed `node_modules` (I usually simply delete the folder and do another `npm install`). You can then generate the module from proto files and apply the fix again afterward.

After files have been generated, I get rid of any `eval` and simply return `undefined`. I am using [ripgrep](https://github.com/BurntSushi/ripgrep) instead of the traditional `grep` here, but it should work very similarly:

```bash
sed -i 's/eval("quire".replace(\/^\/,"re"))(moduleName);/undefined;/g' node_modules/@protobufjs/inquire/index.js

for file in $(rg 'eval\("quire".replace' -l node_modules/protobufjs/); do
  echo $file
  sed -i 's/eval("quire".replace(\/^\/,"re"))(moduleName);/undefined;/g' $file
done
```

The last step solves another undefined bug with the `$root` later on in the generated static module. This is off-topic, but the fix is super simply, so I wanted to mention it here as well:

```bash
sed -i 's/$protobuf.roots\["default"\] || ($protobuf.roots\["default"\] = {})/{}/g' src/lib/api/types.js
```

If you are using [just](https://github.com/casey/just), here are the recipes that fix the issue and make re-generating proto files not too bad. Note, that I have all my UI code in the `frontend` sub-folder:

```just
# If you need to rebuild the proto files, delete the node_modules and execute a new npm install, then it will work again.
build-proto-frontend:
    #!/usr/bin/env bash

    cd frontend
    mkdir -p src/lib/api

    ./node_modules/protobufjs-cli/bin/pbjs \
        --es6 -w es6 \
        -t static-module \
        --no-verify --no-convert --no-delimited --no-service --null-defaults \
        -o src/lib/api/types.js \
        ../proto/*.proto

    # fix a bug to make it work with svelte
    sed -i 's/$protobuf.roots\["default"\] || ($protobuf.roots\["default"\] = {})/{}/g' src/lib/api/types.js

    git add src/lib/api

# cleans up all node_modules and re-installs to get the `eval` back for protobuf compilation
reset-protobufjs:
    #!/usr/bin/env bash

    cd frontend
    rm -rf node_modules
    npm install

# remove all `eval` from the protobufjs library after a fresh installation.
fix-protobufjs-eval:
    #!/usr/bin/env bash
    cd frontend

    sed -i 's/eval("quire".replace(\/^\/,"re"))(moduleName);/undefined;/g' node_modules/@protobufjs/inquire/index.js

    for file in $(rg 'eval\("quire".replace' -l node_modules/protobufjs/); do
      echo $file
      sed -i 's/eval("quire".replace(\/^\/,"re"))(moduleName);/undefined;/g' $file
    done
```

**Comment by NateScarlet** [comment]
simple vite plugin for workaround

```typescript
import type { Plugin } from 'vite';

function protobufPatch(): Plugin {
  return {
    name: 'protobuf-patch',
    transform(code, id) {
      // https://github.com/protobufjs/protobuf.js/issues/1754
      if (id.endsWith('@protobufjs/inquire/index.js')) {
        return code.replace(`eval("quire".replace(/^/,"re"))`, 'require');
      }
      return code;
    },
  };
}
```

**Comment by sherlock1982** [comment]
This should be fixed with #1941 but not yet released

**Comment by Witoso** [comment]
For those that missed it, looks like #1941 and the `eval` removal was shipped in [v7.5.0](https://github.com/protobufjs/protobuf.js/releases/tag/protobufjs-v7.5.0).

**Comment by tomfuertes** [comment]
@Witoso Possible I'm a node noob but seems to still exist in dep tree for google-data use case

![Image](https://github.com/user-attachments/assets/1753c50b-0c39-4d21-b917-5e04af6cfc66)

```
❯ npm list @protobufjs/inquire
example-project@0.0.0 /Users/tomfuertes/sandbox/git-repos/example-project
└─┬ @google-analytics/data@5.1.0
  └─┬ google-gax@5.0.1-rc.1
    └─┬ protobufjs@7.5.0
      ├─┬ @protobufjs/fetch@1.1.0
      │ └── @protobufjs/inquire@1.1.0 deduped
      └── @protobufjs/inquire@1.1.0 <-- still here
```

**Comment by Witoso** [comment]
Eh… I think you're right, it looks like [7.5.0](https://github.com/protobufjs/protobuf.js/pull/1941) was shipped (but it's [not tagged as `latest`](https://www.npmjs.com/package/protobufjs/v/6.7.0?activeTab=versions)?), but inquire was not released...

**Comment by pltoledo** [comment]
Any updates on the `@protobufjs/inquire` release? This issue is blocking some of our work

**Comment by FZambia** [comment]
@mkruskal-google hello, sorry for mentioning, could you please clarify the status of this issue? It seems `protobuf.js` is blocked in some organizations due to eval usage (even if it's not a real security concern here). Avoiding it would be a very nice thing.

Probably just embed `inquire` dependency if releasing a new version of it is a problem? Or is this change concerning from some other perspective?

**Comment by dvanjara** [comment]
Any updates on the @protobufjs/inquire release? This issue is blocking some of our work. Please maintainer look into this matter do release.

**Comment by sc0Vu** [comment]
I think the issue has been solved https://github.com/protobufjs/protobuf.js/issues/2131 https://github.com/protobufjs/protobuf.js/pull/2146.
