### ISSUE TITLE
"length" is outside of buffer bounds

### ISSUE THREAD

**Issue by phaistonian** [protobufjs/protobuf.js#2025]
protobuf.js version: 7.4.0

It appears that the latest nodejs version (22.7.0) triggers this error:

`
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds
`

at

![CleanShot 2024-08-23 at 09 21 15@2x](https://github.com/user-attachments/assets/15d0f50e-bab0-4fbc-b506-b106fb3d43a4)

**Comment by likezero** [comment]
I have  the same error
![image](https://github.com/user-attachments/assets/eabd0f99-adc7-4fbb-8361-d2a7101e810a)

**Comment by markkkkas** [comment]
We are observing same issue
```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds
    at proto.utf8Write (node:internal/buffer:1066:13)
    at Op.writeStringBuffer [as fn] (/app/node_modules/.pnpm/protobufjs@7.2.4/node_modules/protobufjs/src/writer_buffer.js:61:13)
    at BufferWriter.finish (/app/node_modules/.pnpm/protobufjs@7.2.4/node_modules/protobufjs/src/writer.js:453:14)
    at /app/node_modules/.pnpm/@grpc+proto-loader@0.7.6/node_modules/@grpc/proto-loader/build/src/index.js:152:109
    at Array.map (<anonymous>)
    at createPackageDefinition (/app/node_modules/.pnpm/@grpc+proto-loader@0.7.6/node_modules/@grpc/proto-loader/build/src/index.js:152:39)
    at Object.fromJSON (/app/node_modules/.pnpm/@grpc+proto-loader@0.7.6/node_modules/@grpc/proto-loader/build/src/index.js:205:12)
    at GrpcClient.loadProtoJSON (/app/node_modules/.pnpm/google-gax@4.0.3_encoding@0.1.13/node_modules/google-gax/build/src/grpc.js:228:51)
    at new TranslationServiceClient (/app/node_modules/.pnpm/@google-cloud+translate@8.3.0_encoding@0.1.13/node_modules/@google-cloud/translate/build/src/v3/translation_service_client.js:146:38)
    at new GoogleTranslationService (/app/apps/dist/lib/google-translation.js:55:32)
```

**Comment by cecilulysess** [comment]
Same issue, not necessary to protobufjs@7.4. The error thrown on my 7.3.3

**Comment by danielbankhead** [comment]
This sounds like an upstream Node issue:
- https://github.com/nodejs/node/issues/54518

**Comment by nextlevelshit** [comment]
In case you are still experiencing that issues, try these LTS versions:
- v20.17.0 (april '26)
- v18.20.4 (april '25)

Everything above looks from my perspective broken and leads to these buffer errors.

**Comment by mbrevda** [comment]
Also fixed in the latest node (v22.8.0)

**Comment by temirrr** [comment]
@mbrevda thanks, upgrading to v22.8.0 worked for me

**Comment by StiliyanKushev** [comment]
The issue still persists. Please take a look, this should be reopened.
Works with `v22.8.0` but not with `v23.8.0`
